# Generated by Django 3.2.6 on 2021-08-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210806_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumeruserprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produceruserprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
