# Generated by Django 3.2.6 on 2021-08-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210806_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumeruserprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='consumeruserprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='produceruserprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
