# Generated by Django 3.2.6 on 2021-08-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_food_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmfooduser',
            name='is_consumer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmfooduser',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
    ]
