# Generated by Django 3.2.6 on 2021-08-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20210806_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('meat', 'Meat'), ('milk', 'Milk'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit')], default='meat', max_length=9)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('product_image', models.ImageField(upload_to='product')),
                ('producer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.produceruserprofile')),
            ],
        ),
    ]
